#pragma once

using RE::Actor;
using RE::ACTOR_BASE_DATA;
using RE::ActorValue;
using RE::ActorValueInfo;
using RE::BGSColorForm;
using RE::BGSEquipSlot;
using RE::BGSKeyword;
using RE::BGSPerk;
using RE::BGSSkillPerkTreeNode;
using RE::BGSTextureSet;
using RE::BSTArray;
using RE::BSTHashMap;
using RE::Effect;
using RE::EffectSetting;
using RE::FormType;
using RE::PlayerCharacter;
using RE::RACE_DATA;
using RE::RESET_3D_FLAGS;
using RE::SEX;
using RE::SpellItem;
using RE::StaticFunctionTag;
using RE::TESActorBaseData;
using RE::TESDataHandler;
using RE::TESForm;
using RE::TESNPC;
using RE::TESObjectBOOK;
using RE::TESRace;